=== lyplcr/testfarm/core/wizards/config.dtd
<!-- TestFarm System Configuration format -->
<!-- $Revision: 322 $ -->
<!-- $Date: 2006-11-29 14:53:43 +0100 (mer., 29 nov. 2006) $ -->

<!ELEMENT CONFIG (DESCRIPTION?, INFO+, START?, STOP?, SERVICE*, INTERFACE+)>

<!ELEMENT INFO (#PCDATA)>
<!ATTLIST INFO
  id CDATA #REQUIRED
>

<!ELEMENT START (#PCDATA)>

<!ELEMENT STOP (#PCDATA)>

<!ELEMENT STATUS (#PCDATA)>

<!ELEMENT SERVICE (INFO*, START?, STOP?, STATUS?)>
<!ATTLIST SERVICE
  id CDATA #REQUIRED
  cmd CDATA #IMPLIED
  mode (MANUAL|AUTO|ANY|DISABLE) #IMPLIED
>

<!ELEMENT INTERFACE (INFO*, START?, STOP?, FEATURE+)>
<!ATTLIST INTERFACE
  id CDATA #REQUIRED
  type CDATA #REQUIRED
  addr CDATA #IMPLIED
  mode (MANUAL|AUTO|ANY|DISABLE) #IMPLIED
>

<!ELEMENT FEATURE (DESCRIPTION, START?, STOP?, ACTION*)>
<!ATTLIST FEATURE
  id CDATA #REQUIRED
  mode (MANUAL|AUTO|ANY|DISABLE) #IMPLIED
>

<!ELEMENT DESCRIPTION (#PCDATA)>

<!ELEMENT ACTION (#PCDATA)>
<!ATTLIST ACTION
  id CDATA #REQUIRED
  proto CDATA #IMPLIED
>

=== lyplcr/testfarm/vu/test/TVUtest.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="/opt/testfarm/lib/config.xsl"?>
<!DOCTYPE CONFIG SYSTEM "/opt/testfarm/lib/config.dtd">

<!-- $Revision$ -->
<!-- $Date$ -->

<CONFIG>
  <DESCRIPTION>
    TestFarm VU Validation Suite
  </DESCRIPTION>
  <INFO id="System Config Version">
    $Revision$
  </INFO>
  <INTERFACE id="VISU" type="TestFarm::VU" addr="-name VISU file://frames/frame.ppm.gz">
    <INFO id="version" />
    <START>
      sleep 1;
      $I->status();
      $I->mode('prompt', 'on');
      return 0;
    </START>
    <FEATURE id="Display">
      <DESCRIPTION>Display Frame</DESCRIPTION>
      <ACTION id="DisplayFrame" proto="$">
        my $name = shift;
        unlink('frames/frame.ppm.gz');
        my $fname = $name.'.ppm.gz';
        my $ret = symlink($fname, 'frames/frame.ppm.gz');
        if ( $ret ) {
          $I->capture_refresh('now');
          sleep(1);
        }
        else {
          print STDERR "DisplayFrame: failed to create symlink to $fname: $!\n";
        }
        return $ret;
      </ACTION>
    </FEATURE>
  </INTERFACE>
</CONFIG>

=== lyplcr/testfarm/demo/EWD/EWDsystem-vnc.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="/opt/testfarm/lib/config.xsl"?>
<!DOCTYPE CONFIG SYSTEM "/opt/testfarm/lib/config.dtd">

<!-- $Revision$ -->
<!-- $Date$ -->

<CONFIG>
  <DESCRIPTION>
    EWD Demo using a Xvnc Desktop
  </DESCRIPTION>
  <INFO id="System Config Version">
    $Revision$
  </INFO>
  <INFO id="Host Addr">
    127.0.0.1
  </INFO>
  <INFO id="Color Fuzz">
    8
  </INFO>
  <SERVICE id="EWDdisplay">
    <START>
      system('./EWDstart.pl');
      return 0;
    </START>
    <STOP>
      system('killall EWDdisplay.pl');
      return 0;
    </STOP>
  </SERVICE>
  <INTERFACE id="VISU" type="TestFarm::VU" addr="-name VISU-VNC rfb://testfarm\@localhost:1">
    <START>
      sleep 1;
      $I->status();
      $I->capture_refresh(125);
      $I->capture_geometry('600x200+0+0');
      return 0;
    </START>
    <FEATURE id="Display">
      <DESCRIPTION>EWD Display Window</DESCRIPTION>
      <START>
    	use EWDdisplay;
    	EWDdisplay::init($INFO{'Host Addr'});
      </START>
    </FEATURE>
  </INTERFACE>
</CONFIG>

=== lyplcr/testfarm/core/test/InputFlood/InputFlood.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="/opt/testfarm/lib/config.xsl"?>
<!DOCTYPE CONFIG SYSTEM "/opt/testfarm/lib/config.dtd">

<!-- $Revision: 1087 $ -->
<!-- $Date: 2009-10-30 14:59:45 +0100 (ven., 30 oct. 2009) $ -->

<CONFIG>
  <DESCRIPTION>
    TestFarm System Configuration for Input Flood testings
  </DESCRIPTION>
  <INFO id="Revision">
    $Revision: 1087 $
  </INFO>
  <INTERFACE id="PERIODIC1" type="PeriodicSend">
    <INFO id="version" />
    <FEATURE id="PeriodicMessage1">
      <DESCRIPTION>First periodic message source</DESCRIPTION>
      <START>
        return 0;
      </START>
    </FEATURE>
  </INTERFACE>
  <INTERFACE id="PERIODIC2" type="PeriodicSend">
    <INFO id="version" />
    <FEATURE id="PeriodicMessage2">
      <DESCRIPTION>Second periodic message source</DESCRIPTION>
      <START>
        return 0;
      </START>
    </FEATURE>
  </INTERFACE>
  <INTERFACE id="PERIODIC3" type="PeriodicSend">
    <INFO id="version" />
    <FEATURE id="PeriodicMessage3">
      <DESCRIPTION>Third periodic message source</DESCRIPTION>
      <START>
        return 0;
      </START>
    </FEATURE>
  </INTERFACE>
</CONFIG>

=== lyplcr/testfarm/core/test/config/TestSystem.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="/opt/testfarm/lib/config.xsl"?>
<!DOCTYPE CONFIG SYSTEM "/opt/testfarm/lib/config.dtd">

<!-- $Revision: 657 $ -->
<!-- $Date: 2007-07-25 09:08:42 +0200 (mer., 25 juil. 2007) $ -->

<CONFIG>
  <DESCRIPTION>
    Sample TestFarm System Configuration
  </DESCRIPTION>
  <INFO id="Revision">
    $Revision: 657 $
  </INFO>
  <INTERFACE id="INTERFACE" type="Echo">
    <INFO id="serial">
      001
    </INFO>
    <INFO id="version" />
    <FEATURE id="Message">
      <DESCRIPTION>Dump a Message</DESCRIPTION>
      <START>
        return 0;
      </START>
      <STOP>
      </STOP>
      <ACTION id="Echo">
        $I->echo("@_");
      </ACTION>
      <ACTION id="TrigEcho" proto="$">
        return $I->TrigDef('ECHO', "ECHO +@_");
      </ACTION>
    </FEATURE>
  </INTERFACE>
</CONFIG>

=== lyplcr/testfarm/demo/EWD/EWDsystem-dvi.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="/opt/testfarm/lib/config.xsl"?>
<!DOCTYPE CONFIG SYSTEM "/opt/testfarm/lib/config.dtd">

<!-- $Revision$ -->
<!-- $Date$ -->

<CONFIG>
  <DESCRIPTION>
    EWD Demo using a DVI Frame Grabber
  </DESCRIPTION>
  <INFO id="System Config Version">
    $Revision$
  </INFO>
  <INFO id="Host Addr">
    192.168.20.102
  </INFO>
  <INFO id="Color Fuzz">
    8
  </INFO>
  <INFO id="Pixel Loss">
    1
  </INFO>
  <SERVICE id="EWDdisplay">
    <START>
    </START>
    <STOP>
    </STOP>
  </SERVICE>
  <INTERFACE id="VISU" type="TestFarm::VU" addr="-name VISU-DVI v4l://:1">
    <START>
      sleep 1;
      $I->status();
      $I->capture_refresh(125);
      $I->capture_geometry('600x200+5+48');
      return 0;
    </START>
    <FEATURE id="Display">
      <DESCRIPTION>EWD Display Window</DESCRIPTION>
      <START>
    	use EWDdisplay;
    	EWDdisplay::init($INFO{'Host Addr'});
      </START>
    </FEATURE>
  </INTERFACE>
</CONFIG>
